// This code generated by Sds\DoctrineExtensions\DojoModel

define ([
        'dojo/_base/declare',
        'dojo/Stateful'
    ],
    function (
        declare,
        Stateful
    ){
        // module:
        //		Sds/DoctrineExtensions/Test/DojoModel/TestAsset/Document/ClassName

        return declare (
            'Sds.DoctrineExtensions.Test.DojoModel.TestAsset.Document.ClassName',
            [Stateful],
            {
                // summary:
                //		A mirror of doctrine document Sds\DoctrineExtensions\Test\DojoModel\TestAsset\Document\ClassName
                //
                // description:
                //      Use this to create documents in a browser which can the be passed to a doctrine server for
                //      persistence

                // _className: string
                //      The doctrine document class name. Don't change this one!
                _className: 'Sds\\DoctrineExtensions\\Test\\DojoModel\\TestAsset\\Document\\ClassName',

                // id: custom_id
                id: undefined,

                // name: string
                name: undefined,

                toJSON: function(){
                    // summary:
                    //     Function to handle serialization

                    var json = {};
                    if (this.get('_className')) {
                        json['_className'] = this.get('_className');
                    }
                    if (this.get('id')) {
                        json['id'] = this.get('id');
                    }
                    if (this.get('name')) {
                        json['name'] = this.get('name');
                    }

                    return json;
                }
            }
        );
    }
);
