// This code generated by Sds\DoctrineExtensions\DojoModel

define ([
    'dojo/_base/declare',
    'dojo/Stateful',
        'me/myModule1',
        'me/myModule2'
],
function (
    declare,
    Stateful,
        MemyModule1,
        MemyModule2
){
    // module:
    //		Sds/DoctrineExtensions/Test/DojoModel/TestAsset/Document/Simple

    return declare (
        'Sds/DoctrineExtensions/Test/DojoModel/TestAsset/Document/Simple',
        [Stateful, MemyModule1, MemyModule2],
        {
            // summary:
            //		A mirror of doctrine document Sds\DoctrineExtensions\Test\DojoModel\TestAsset\Document\Simple
            //
            // description:
            //      Use this to create documents in a browser which can the be passed to a doctrine server for
            //      persistence

                // _className: string
                //      The doctrine document class name. Don't change this one!
                _className: 'Sds\\DoctrineExtensions\\Test\\DojoModel\\TestAsset\\Document\\Simple',

                // id: custom_id
                id: undefined,

                // name: string
                name: undefined,

                // country: string
                country: undefined,

                // camelCaseProperty: string
                camelCaseProperty: undefined,

            toJSON: function(){
                // summary:
                //     Function to handle serialization

                var json = {};
                    if (this.get('_className')) {
                        json['_className'] = this.get('_className');
                    }
                    if (this.get('_')) {
                        json['_'] = this.get('_');
                    }
                    if (this.get('id')) {
                        json['id'] = this.get('id');
                    }
                    if (this.get('name')) {
                        json['name'] = this.get('name');
                    }
                    if (this.get('country')) {
                        json['country'] = this.get('country');
                    }
                    if (this.get('camelCaseProperty')) {
                        json['camelCaseProperty'] = this.get('camelCaseProperty');
                    }

                return json;
            }
        }
    );
});
