<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class Sds\DoctrineExtensionsTestSoftDeleteTestAssetDocumentStampedHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="custom_id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name'])) {
            $value = $data['name'];
            $return = (string) $value;
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['softDeleted'])) {
            $value = $data['softDeleted'];
            $return = (bool) $value;
            $this->class->reflFields['softDeleted']->setValue($document, $return);
            $hydratedData['softDeleted'] = $return;
        }

        /** @Field(type="timestamp") */
        if (isset($data['softDeletedOn'])) {
            $value = $data['softDeletedOn'];
            $return = $value;
            $this->class->reflFields['softDeletedOn']->setValue($document, $return);
            $hydratedData['softDeletedOn'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['softDeletedBy'])) {
            $value = $data['softDeletedBy'];
            $return = (string) $value;
            $this->class->reflFields['softDeletedBy']->setValue($document, $return);
            $hydratedData['softDeletedBy'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['restoredBy'])) {
            $value = $data['restoredBy'];
            $return = (string) $value;
            $this->class->reflFields['restoredBy']->setValue($document, $return);
            $hydratedData['restoredBy'] = $return;
        }

        /** @Field(type="timestamp") */
        if (isset($data['restoredOn'])) {
            $value = $data['restoredOn'];
            $return = $value;
            $this->class->reflFields['restoredOn']->setValue($document, $return);
            $hydratedData['restoredOn'] = $return;
        }
        return $hydratedData;
    }
}