<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class SdsDoctrineExtensionsAuditModelAuditHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="custom_id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['oldValue'])) {
            $value = $data['oldValue'];
            $return = (string) $value;
            $this->class->reflFields['oldValue']->setValue($document, $return);
            $hydratedData['oldValue'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['newValue'])) {
            $value = $data['newValue'];
            $return = (string) $value;
            $this->class->reflFields['newValue']->setValue($document, $return);
            $hydratedData['newValue'] = $return;
        }

        /** @Field(type="timestamp") */
        if (isset($data['changedOn'])) {
            $value = $data['changedOn'];
            $return = $value;
            $this->class->reflFields['changedOn']->setValue($document, $return);
            $hydratedData['changedOn'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['changedBy'])) {
            $value = $data['changedBy'];
            $return = (string) $value;
            $this->class->reflFields['changedBy']->setValue($document, $return);
            $hydratedData['changedBy'] = $return;
        }
        return $hydratedData;
    }
}