// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Form/TextBox'
],
function(
    declare,
    TextBox
){
    // Will return an Input for the id field

    return declare(
        Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Id/Input,
        [TextBox],
        {
            name: "id",

            label: "Id:",

            type: "hidden"
        }
    );
});
