// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Validator/ValidatorGroup',
    'Sds/Common/Validator/RequiredValidator',
    'Sds/Test/NameValidator1',
    'Sds/Test/NameValidator2'
],
function(
    declare,
    ValidatorGroup,
    RequiredValidator,
    NameValidator1,
    NameValidator2
){
    // Will return a validator that can be used to check
    // the name field

    return declare(
        'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Name/Validator',
        [ValidatorGroup],
        {
            field: "name",

            validators: [
                new RequiredValidator,
                new NameValidator1,
                new NameValidator2({
                    "option1": "b",
                    "option2": "b"
                })
            ]
        }
    );
});
