// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Form/TextBox'
],
function(
    declare,    
    TextBox
){
    // Will return an input for the camelCaseProperty field

    return declare(
        [            
            TextBox        
        ],
        {
            name: 'camelCaseProperty',
            
            label: 'Camel Case Property'
        }
    );
});
