// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Form/ValidationForm',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/MultiFieldValidator',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Id/Input',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Name/Input',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Country/Input',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/CamelCaseProperty/Input'
],
function(
    declare,
    ValidationForm,
    MultiFieldValidator,
    IdInput,
    NameInput,
    CountryInput,
    CamelCasePropertyInput
){
    // Will return a form

    return declare(
        'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Form',
        [ValidationForm],
        {

            validator: new MultiFieldValidator,

            inputs: [
                new IdInput,
                new NameInput,
                new CountryInput,
                new CamelCasePropertyInput
            ]
        }
    );
});
