// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Form/ValidationControlGroup',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/MultiFieldValidator',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Id/Input',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Name/Input',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Country/Input',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/CamelCaseProperty/Input'
],
function(
    declare,    
    ValidationControlGroup,
    MultiFieldValidator,
    IdInput,
    NameInput,
    CountryInput,
    CamelCasePropertyInput
){
    // Will return a form for Sds\DoctrineExtensions\Test\Dojo\TestAsset\Document\Simple

    return declare(
        'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Form',
        [            
            ValidationControlGroup        
        ],
        {
            validator: new MultiFieldValidator,
            
            inputs: [
            	new IdInput,
            	new NameInput,
            	new CountryInput,
            	new CamelCasePropertyInput
            ]
        }
    );
});
