// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Mvc/BaseModelJsonRestStore',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple'
],
function(
    declare,
    BaseJsonRestStore,
    Simple
){
    // Will return dojo object store to manage server model
    // instances with a json rest api.

    return declare(
        'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/JsonRestStore',
        [BaseJsonRestStore],
        {

            idProperty: 'id',

            target: 'Simple',

            model: Simple
        }
    );
});
