// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Mvc/JsonRest',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple'
],
function(
    declare,    
    JsonRest,
    Simple
){
    // Will return create a dojo JsonRest store for Sds\DoctrineExtensions\Test\Dojo\TestAsset\Document\Simple

    return declare(
        [            
            JsonRest        
        ],
        {
            name: 'Simple',
            
            idField: 'id',
            
            target: 'Simple',
            
            model: Simple
        }
    );
});
