// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Validator/ModelValidator',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/MultiFieldValidator',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Name/Validator',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Country/Validator'
],
function(
    declare,    
    ModelValidator,
    MultiFieldValidator,
    NameValidator,
    CountryValidator
){
    // Will return a validator to validate a complete model for Sds\DoctrineExtensions\Test\Dojo\TestAsset\Document\Simple

    return declare(
        'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/ModelValidator',
        [            
            ModelValidator        
        ],
        {
            validators: [
            	new MultiFieldValidator,
            	new NameValidator,
            	new CountryValidator
            ]
        }
    );
});
