// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',
    'Sds/Common/Validator/ValidatorGroup',
    'Sds/Test/ClassValidator1',
    'Sds/Test/ClassValidator2'
],
function(
    declare,
    ValidatorGroup,
    ClassValidator1,
    ClassValidator2
){
    // Will return a validator that can be used to check any
    // validations that require multiple fields

    return declare(
        'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/MultiFieldValidator',
        [ValidatorGroup],
        {
            validators: [
                new ClassValidator1,
                new ClassValidator2({
                    "option1": "a",
                    "option2": "b"
                })
            ]
        }
    );
});