// This code generated by Sds\DoctrineExtensions\Dojo

define ([], function (){

    return {
        moduleManager: {

            // Will return an object representing the document
            // which can be serialized to json.
            'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple': {
                base: 'Sds/Mvc/BaseModel',
                directives: {
                    declare: true
                },
                params: {
                    _fields: [
                        "id",
                        "name",
                        "country",
                        "camelCaseProperty",
                        "_className"
                    ],
                    _className: 'Sds\\DoctrineExtensions\\Test\\Dojo\\TestAsset\\Document\\Simple'
                }
            },

            // Will return an validator that can be used to validate
            // a complete instance of the document/model
            'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/validator': {
                base: 'modelValidator',
                gets: {
                    validators: [
                        "Sds\/DoctrineExtensions\/Test\/Dojo\/TestAsset\/Document\/Simple\/multiFieldValidator",
                        "Sds\/DoctrineExtensions\/Test\/Dojo\/TestAsset\/Document\/Simple\/Name\/validator",
                        "Sds\/DoctrineExtensions\/Test\/Dojo\/TestAsset\/Document\/Simple\/Country\/validator"
                    ]
                }
            },

            // Will return a validator that can be used to check any
            // validations that require multiple fields
            'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/multiFieldValidator': {
                "base": "validatorGroup",
                "gets": {
                    "validators": [
                        "Sds\/Test\/ClassValidator1",
                        {
                            "base": "Sds\/Test\/ClassValidator2",
                            "params": {
                                "option1": "a",
                                "option2": "b"
                            }
                        }
                    ]
                }
            },

            // Will return a validator that can be used to check
            // the name field
            'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Name/validator': {
                "base": "validatorGroup",
                "gets": {
                    "validators": [
                        "Sds\/Common\/Validator\/RequiredValidator",
                        "Sds\/Test\/NameValidator1",
                        {
                            "base": "Sds\/Test\/NameValidator2",
                            "params": {
                                "option1": "b",
                                "option2": "b"
                            }
                        }
                    ]
                },
                "params": {
                    "field": "name"
                }
            },

            // Will return a validator that can be used to check
            // the country field
            'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Country/validator': {
                "base": "Sds\/Test\/CountryValidator1",
                "gets": {
                    "validators": [
                        "Sds\/Common\/Validator\/NotRequiredValidator"
                    ]
                },
                "params": {
                    "field": "country"
                }
            },

            // Will return a form
            'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Form': {
                "base": "Sds\/Common\/Form\/ValidationForm",
                "directives": {
                    "define": true,
                    "declare": true
                },
                "gets": {
                    "validator": "Sds\/DoctrineExtensions\/Test\/Dojo\/TestAsset\/Document\/Simple\/multiFieldValidator",
                    "inputs": [
                        "Sds\/DoctrineExtensions\/Test\/Dojo\/TestAsset\/Document\/Simple\/Id\/Input",
                        "Sds\/DoctrineExtensions\/Test\/Dojo\/TestAsset\/Document\/Simple\/Name\/Input",
                        "Sds\/DoctrineExtensions\/Test\/Dojo\/TestAsset\/Document\/Simple\/Country\/Input",
                        "Sds\/DoctrineExtensions\/Test\/Dojo\/TestAsset\/Document\/Simple\/CamelCaseProperty\/Input"
                    ]
                }
            },

            // Will return an Input for the id field
            'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Id/Input': {
                "base": "Sds\/Common\/Form\/TextBox",
                "directives": {
                    "define": true,
                    "declare": true
                },
                "params": {
                    "name": "id",
                    "label": "Id:",
                    "type": "hidden"
                }
            },

            // Will return an Input for the name field
            'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Name/Input': {
                "base": "Sds\/Common\/Form\/ValidationTextBox",
                "gets": {
                    "validator": "Sds\/DoctrineExtensions\/Test\/Dojo\/TestAsset\/Document\/Simple\/Name\/validator"
                },
                "directives": {
                    "define": true,
                    "declare": true
                },
                "params": {
                    "name": "name",
                    "label": "NAME",
                    "tooltip": "The simple's name",
                    "description": "This is a longer description"
                }
            },

            // Will return an Input for the country field
            'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Country/Input': {
                "base": "Sds\/Common\/Form\/ValidationTextarea",
                "gets": {
                    "validator": "Sds\/DoctrineExtensions\/Test\/Dojo\/TestAsset\/Document\/Simple\/Country\/validator"
                },
                "directives": {
                    "define": true,
                    "declare": true
                },
                "params": {
                    "name": "country",
                    "label": "Country:"
                }
            },

            // Will return an Input for the camelCaseProperty field
            'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/CamelCaseProperty/Input': {
                "base": "Sds\/Common\/Form\/TextBox",
                "directives": {
                    "define": true,
                    "declare": true
                },
                "params": {
                    "name": "camelCaseProperty",
                    "label": "Camel Case Property:"
                }
            }
        }
    };
});
