// This code generated by Sds\DoctrineExtensions\DojoModel

define ([
        'dojo/_base/declare',
        'dojo/_base/Stateful'
    ],
    function (
        declare,
        Stateful
    ){
        // module:
        //		Sds/DoctrineExtensions/Test/DojoModel/TestAsset/Document/Simple

        return declare (
            'Sds.DoctrineExtensions.Test.DojoModel.TestAsset.Document.Simple',
            [Stateful],
            {
                // summary:
                //		A mirror of doctrine document Sds\DoctrineExtensions\Test\DojoModel\TestAsset\Document\Simple
                //
                // description:
                //      Use this to create documents in a browser which can the be passed to a doctrine server for
                //      persistence

                // id: custom_id
                id: undefined,

                // name: string
                name: undefined

            }
        );
    }
);
