// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Form/ValidationTextBox',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Country/Validator'
],
function(
    declare,    
    ValidationTextBox,
    CountryValidator
){
    // Will return an input for the country field

    return declare(
        'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Country/Input',
        [            
            ValidationTextBox        
        ],
        {
            validator: new CountryValidator,
            
            name: 'country',
            
            label: 'Country:'
        }
    );
});
