// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Common/Form/ValidationTextarea',
    'Sds/DoctrineExtensions/Test/Dojo/TestAsset/Document/Simple/Country/Validator'
],
function(
    declare,    
    ValidationTextarea,
    CountryValidator
){
    // Will return an input for the country field

    return declare(
        [            
            ValidationTextarea        
        ],
        {
            validator: new CountryValidator,
            
            name: 'country',
            
            label: 'Country'
        }
    );
});
