// This code generated by Sds\DoctrineExtensions\Dojo
define([
    'dojo/_base/declare',    
    'Sds/Form/TextBox'
],
function(
    declare,    
    TextBox
){
    // Will return an input for the camelCaseField field

    return declare(
        [            
            TextBox        
        ],
        {
            name: 'camelCaseField',
            
            label: 'Camel Case Field'
        }
    );
});
